GET https://www.baidu.com HTTP/1.1

###
GET http://127.0.0.1:5555/getsession HTTP/1.1
Accept: application/json
Content-Type: application/json

###
POST http://127.0.0.1:5555/pushsession
Content-Type: application/json

{
    "token":"YSwGII4R0nZMzTnuCD02mnQ0LAmJ3w6DOcpdcq98XL7NLilm+vwmc5PdMTo8ktg7MWpbLTlRLpP8/aUgx66b3cfeigYTo3xpfqsZw1nPeYq44c7VuepyD0R+jyLlVXyXvcaYo7h1Ct3iiLSWlyv132MM/5oad+aiGMRBzXWfV0s=",
    "session_id":"OAxHIu0rU6oEV7P5hufOpZijQBFtV3raOUJkCZgINhc",
    "session_name":"test",
    "session_command":"test"
}