GET https://www.baidu.com HTTP/1.1

###
GET http://127.0.0.1:5555/getsession HTTP/1.1
Accept: application/json
Content-Type: application/json

###
POST http://127.0.0.1:5555/pushsession
Content-Type: application/json

{
    "token":"D0HW0aY/n3qT8UTyWFWEXP2dBLQh+6QMIctYiTD9y1TglvzXF1Deekkw+fYFmy2mRV3jKbGq40wCYQ4gaCu6K7KW0DphUoT2Dc7qce2CdSW0BUwGtzyQ61hty66aHZsVfr9DTmmzoR0l0ZGnThFLF1pqatJKUsi/J9/N3TZ+HGI=",
    "session_id":"Iwq2qZT7PuT9M701xwI8pTOHwqk7A9FrqMioWt_tp1c",
    "session_name":"test",
    "session_command":"test"
}